### ISSUE TITLE
Emojis for Haskell, Purescript?

### ISSUE THREAD

**Issue by axman6** [buildkite/emojis#165]
Looks like many languages have icons, would be good to get these two.

**Comment by ticky** [comment]
HI @axman6, we’d definitely accept a PR for this! :)

**Comment by axman6** [comment]
@ticky Any chance of getting #166 merged? Our builds look so ugly with all there's `:Haskell:`'s sitting around :'(

**Comment by keithpitt** [comment]
@axman6 I merged the PR!
