### ISSUE TITLE
Terraform & Packer emojis

### ISSUE THREAD

**Issue by pdeaudney** [buildkite/emojis#22]
Some emoji for Terraform & Packer would be great.

- https://www.terraform.io/
- https://www.packer.io/

Thanks

**Comment by keithpitt** [comment]
Hey @pdeaudney, we already have the :packer: and :terraform: emoji awaiting your usage 👯 

<img width="373" alt="screen shot 2016-06-07 at 6 53 53 pm" src="https://cloud.githubusercontent.com/assets/25882/15851706/43523a9e-2ce1-11e6-98da-e2139d924181.png">

**Comment by holynakamoto** [comment]
:terraform:
