### ISSUE TITLE
Support puppeteer icon

### ISSUE THREAD

**Issue by felixfbecker** [buildkite/emojis#226]
Puppeteer is a popular tool used for e2e testing: https://github.com/GoogleChrome/puppeteer

It has a logo:

![puppeteer logo](https://user-images.githubusercontent.com/10379601/29446482-04f7036a-841f-11e7-9872-91d1fc2ea683.png)

Would be great to support it as an emoji for steps!

**Comment by ticky** [comment]
Hi @felixfbecker, we'd gladly accept a PR adding this!

**Comment by frogamic** [comment]
I've opened #238 the puppeteer logo doesn't scale very well though with all the fine detail.

**Comment by abhidp** [comment]
Dear Buildkite Emoji Repo Owner, 

Can you please approve/reject PR#238 for Puppeteer emoji? 
It has been pending over a month now. 

Yours Sincerely,
Buildkite User

**Comment by ticky** [comment]
Done in #238
