### ISSUE TITLE
Emoji not rendering locally

### ISSUE THREAD

**Issue by wgroenewald** [buildkite/emojis#252]
When doing `bk local run` the :amazon-cognito: emoji does not render, while other emoji's do. Could this be an issue with the emoji itself?

bk version = 1.0.0

**Comment by sj26** [comment]
Thanks for the report! Sounds like it's a bug in https://github.com/buildkite/cli. I believe it's because of the dash. I've filed an issue over there, please follow that one: https://github.com/buildkite/cli/issues/99
