### ISSUE TITLE
Changing / Adding GitHub Logo

### ISSUE THREAD

**Issue by gencer** [buildkite/emojis#282]
When I use `:github:` to indicate GitHub-based operatipons, I see octocat instead of actual logo.

I have 2 proposals:

1. Rename `:github:` to `:octocat:` and add `:github:` for actual circled-GitHub logo.
2. Replace `:github:` logo and only use it without octocat.

Can we do one of these?

/attn @jayco

**Comment by pda** [comment]
[Official GitHub branding](https://github.com/logos):
![image](https://user-images.githubusercontent.com/15759/96400954-d9102e80-121d-11eb-9b2b-82b7b61d0e9c.png)

So you're suggesting `:github:` refer to their **mark** (silhouette of octocat in circle), and `:octocat:` can remain the illustration of the octocat.

Sounds pretty sensible to me.

**Comment by gencer** [comment]
Hey @pda 

Exactly. `:github:` should refer their **mark**, and :octocat: is for actual `octocat`.

I see that @scopegate already sent a PR.

**Comment by pda** [comment]
👍🏼

(Interesting that GitHub has `:octocat:` :octocat: but doesn't have anything for `:github:`)

**Comment by gencer** [comment]
Yeah. That is strange. One thing that came to my mind, **maybe**, they didn't want to expose their trademark for comments and PR's to reduce incorrect/non-legal use (perhaps) instead they used octocat to refer GitHub.

_Can't wait to use it with my pipelines. I just love Buildkite and Emojis with it <3_
