### ISSUE TITLE
Buildkite seems to be applying some weird kerning to emoji that are not solid squares or circles

### ISSUE THREAD

**Issue by snoblenet** [buildkite/emojis#302]
Buildkite seems to be applying some weird kerning to emoji that are not solid squares or circles.

I've tried using double spaces but it makes no difference.

![image](https://user-images.githubusercontent.com/62277/108940037-cbc0f000-76a6-11eb-88d5-59aa99d98dcc.png)

**Comment by yob** [comment]
Thanks @snoblenet. Weird! 

I don't see that on my browser, but I'm on a rare combo (linux and Firefox). Could you share the browser version and OS you're seeing that on?

**Comment by snoblenet** [comment]
Mac OS X 11.2.1
Google Chrome 88.0.4324.192 (Official Build) (x86_64)

(in other words, the latest version of each)

Also I scanned my extensions and none would obviously alter the DOM in a way that might be relevant.

**Comment by ticky** [comment]
Hey @snoblenet,

This is related to an ongoing Chrome bug with emoji rendering on non-retina displays on macOS: https://bugs.chromium.org/p/chromium/issues/detail?id=596223

We render Unicode emoji using the plain Unicode characters, and whatever spacing the browser renders is what we end up with. In the case of our custom emoji, we add a small margin to attempt to emulate the innate emoji spacing present in every case *except* non-retina macOS, and I’d hoped that Google would eventually fix this to match the other cases, as the fix on our end would be fragile but it’s been years and years!
