### ISSUE TITLE
Please good sir add the electron logo

### ISSUE THREAD

**Issue by trashhalo** [buildkite/emojis#33]
![please](https://cloud.githubusercontent.com/assets/177491/17783164/c337b4dc-6544-11e6-84a9-30b5dac12da9.gif)

asset for making the emoji
https://github.com/electron/electron.atom.io/blob/gh-pages/images/electron-icon.svg

**Comment by keithpitt** [comment]
![image](https://cloud.githubusercontent.com/assets/25882/17796484/2dfdf604-6604-11e6-97d6-a550005de302.png)

Added :electron:!

Also - we're not just "sirs" anymore :P
