### ISSUE TITLE
Please add Test Analytics emoji

### ISSUE THREAD

**Issue by mokagio** [buildkite/emojis#388]
I'm loving Test Analytics. 

Because of our setup, the same command exports a different token to route reports to the appropriate suite depending on _stuff_.

I'd love to have an `echo '--- :test-analytics: Configure Test Analytics'` line in my logs 😅 🙇‍♂️

**Comment by meiqimichelle** [comment]
@mokagio -- so happy to hear that you're enjoying Test Analytics 🎉. Let's see what we can do about an emoji, please hold..... :D

**Comment by JuanitoFatas** [comment]
Thanks for show your kindness and opened this issue 💚 

We shipped the Test Analytics emoji, you could use it `:test-analytics:` on Buildkite. 

Enjoy 😊

**Comment by mokagio** [comment]
💚 Thanks @meiqimichelle @JuanitoFatas 🎉

**Comment by mokagio** [comment]
Thank you so much for adding `:test-analytics` 🙇‍♂️ 

Just FYI, the dark color doesn't work too well in the logs:

<img width="457" alt="image" src="https://user-images.githubusercontent.com/1218433/177908972-71aa9675-263b-4e87-8067-9a5e04d92513.png">

I acknowledge this is a super nitpick and have no expectation you'll address this, soon or ever. Only wanted to let you know just in case.

👋
