### ISSUE TITLE
Some newer custom emojis are not rendering in the web UI

### ISSUE THREAD

**Issue by jarpy** [buildkite/emojis#399]
## Input

```
Jarpy Experiments :giraffe_face: :buildah: :planetscale: :openapi:
```

## Output
![image](https://user-images.githubusercontent.com/119659/181854340-53ab4f18-2d7f-4153-84c5-89caf43eb21e.png)

**Comment by yob** [comment]
Thanks for pointing this out @jarpy. I've tracked down what happened and have a proposed fix - I should be able to get through the review gauntlet and into production Monday morning AU time.

**Comment by jarpy** [comment]
Cheers, @yob. Not exactly an urgent, production-impacting issue, but I miss my cute Buildah dog.

:heart:

**Comment by yob** [comment]
@jarpy I believe this has been fixed, thanks again for flagging it!

**Comment by jarpy** [comment]
Thanks. Everything is cute again. Happy Monday.
