### ISSUE TITLE
:allure: emoji is not rendered in log group header

### ISSUE THREAD

**Issue by oleksii-fedorenko-94** [buildkite/emojis#562]
Hi! 😃 
I wanted to use the :allure: emoji in a gropu header like `echo "--- :allure: Generating Allure HTML report"` or `echo "+++ :allure: Generating Allure HTML report"`, but I found out that the emoji is not rendered on the output:

<img width="344" alt="image" src="https://github.com/buildkite/emojis/assets/114982464/df83e3fc-7df8-4b56-bf3e-5094b5a82286">

**Comment by jfhinchcliffe** [comment]
Heya @oleksii-fedorenko-94 . New emojis don't appear immediately in the Buildkite app, but if you check again it should be working now 😁

**Comment by oleksii-fedorenko-94** [comment]
Yes, good now. Thanks for the info 😃
