### ISSUE TITLE
Update Node JS Emoji

### ISSUE THREAD

**Issue by keithpitt** [buildkite/emojis#7]
They've got a new logo!

https://nodejs.org/en/blog/weekly-updates/weekly-update.2016-02-22/#new-official-node-js-logo

**Comment by toolmantim** [comment]
Really not sure which one to use… https://www.google.com.au/search?q=node+js+logo+icon&client=safari&rls=en&biw=2122&bih=1153&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi_me6Z3-TLAhWCwY4KHU66BakQ_AUIBigB

**Comment by keithpitt** [comment]
Maybe we chop out the green hexagon from the main logo?

**Comment by keithpitt** [comment]
<img width="240" alt="screen shot 2016-03-29 at 12 35 07 pm" src="https://cloud.githubusercontent.com/assets/25882/14095313/b05c5a70-f5aa-11e5-98f8-53900335525e.png">

**Comment by toolmantim** [comment]
Yah, good idea! Shipped! :rocket:
